# SPDX-FileCopyrightText: Copyright (c) 2021-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Standalone analyzer for OpenVLA Franka calibration CSV logs.
# This intentionally avoids Isaac Sim imports so it can run in normal Python.

from __future__ import annotations

import argparse
import csv
import math
from collections import Counter
from pathlib import Path
from typing import Iterable


VLA_ACTION_FIELDS = [
    "vla_dx",
    "vla_dy",
    "vla_dz",
    "vla_droll",
    "vla_dpitch",
    "vla_dyaw",
    "vla_gripper",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze observer-only OpenVLA Franka calibration CSV logs."
    )
    parser.add_argument(
        "--csv",
        required=True,
        type=Path,
        help="Path to calibration.csv generated by vla_pick_place.py.",
    )
    return parser.parse_args()


def to_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        result = float(text)
    except ValueError:
        return None
    if not math.isfinite(result):
        return None
    return result


def parse_boolish(value: object) -> bool:
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def format_range(values: Iterable[float]) -> str:
    vals = list(values)
    if not vals:
        return "n/a"
    return f"{min(vals):.6g} .. {max(vals):.6g}"


def format_number(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.6g}"


def mean(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def vector3(row: dict[str, str], prefix: str) -> tuple[float, float, float] | None:
    values = (
        to_float(row.get(f"{prefix}_x")),
        to_float(row.get(f"{prefix}_y")),
        to_float(row.get(f"{prefix}_z")),
    )
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def distance_3d(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return math.sqrt(sum((left - right) ** 2 for left, right in zip(a, b)))


def is_missing_image(row: dict[str, str], csv_path: Path) -> bool:
    raw_path = (row.get("image_path") or "").strip()
    if not raw_path:
        return True

    image_path = Path(raw_path)
    if not image_path.is_absolute():
        image_path = csv_path.parent / image_path
    return not image_path.exists()


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def analyze(csv_path: Path) -> dict[str, object]:
    rows = load_rows(csv_path)

    run_ids = {row.get("run_id", "") for row in rows if row.get("run_id", "") != ""}
    phases = Counter(row.get("phase", "unknown") or "unknown" for row in rows)

    queried_rows = [row for row in rows if parse_boolish(row.get("vla_queried"))]
    vla_error_count = sum(1 for row in queried_rows if (row.get("vla_error") or "").strip())

    vla_success_count = 0
    vla_incomplete_count = 0
    for row in queried_rows:
        action = [to_float(row.get(field)) for field in VLA_ACTION_FIELDS]
        has_error = bool((row.get("vla_error") or "").strip())
        if all(value is not None for value in action) and not has_error:
            vla_success_count += 1
        elif not has_error:
            vla_incomplete_count += 1

    cube_x = [value for row in rows if (value := to_float(row.get("cube_x"))) is not None]
    cube_y = [value for row in rows if (value := to_float(row.get("cube_y"))) is not None]
    target_x = [value for row in rows if (value := to_float(row.get("target_x"))) is not None]
    target_y = [value for row in rows if (value := to_float(row.get("target_y"))) is not None]

    missing_images = sum(1 for row in rows if is_missing_image(row, csv_path))
    latencies_ms = [value for row in rows if (value := to_float(row.get("vla_latency_ms"))) is not None]

    ee_goal_distances: list[float] = []
    for row in rows:
        ee_pos = vector3(row, "ee_pos")
        scripted_goal = vector3(row, "scripted_ee_goal")
        if ee_pos is not None and scripted_goal is not None:
            ee_goal_distances.append(distance_3d(ee_pos, scripted_goal))

    return {
        "csv_path": csv_path,
        "row_count": len(rows),
        "run_count": len(run_ids),
        "phases": phases,
        "vla_queried_count": len(queried_rows),
        "vla_success_count": vla_success_count,
        "vla_error_count": vla_error_count,
        "vla_incomplete_count": vla_incomplete_count,
        "cube_x": cube_x,
        "cube_y": cube_y,
        "target_x": target_x,
        "target_y": target_y,
        "missing_images": missing_images,
        "latencies_ms": latencies_ms,
        "ee_goal_distances": ee_goal_distances,
    }


def print_report(report: dict[str, object]) -> None:
    phases = report["phases"]
    assert isinstance(phases, Counter)

    ee_goal_distances = report["ee_goal_distances"]
    assert isinstance(ee_goal_distances, list)
    latencies_ms = report["latencies_ms"]
    assert isinstance(latencies_ms, list)

    phase_report = ", ".join(f"{phase}={count}" for phase, count in sorted(phases.items()))
    if not phase_report:
        phase_report = "n/a"

    print("VLA Calibration Report")
    print(f"CSV: {report['csv_path']}")
    print(f"Rows: {report['row_count']}")
    print(f"Runs: {report['run_count']}")
    print(f"Phases: {phase_report}")
    print()
    print("VLA")
    print(f"Queried: {report['vla_queried_count']}")
    print(f"Success: {report['vla_success_count']}")
    print(f"Errors: {report['vla_error_count']}")
    print(f"Incomplete actions: {report['vla_incomplete_count']}")
    print(f"Latency samples: {len(latencies_ms)}")
    print(f"Latency mean ms: {format_number(mean(latencies_ms))}")
    print(f"Latency max ms: {format_number(max(latencies_ms) if latencies_ms else None)}")
    print()
    print("Scene Coverage")
    print(f"Cube X: {format_range(report['cube_x'])}")
    print(f"Cube Y: {format_range(report['cube_y'])}")
    print(f"Target X: {format_range(report['target_x'])}")
    print(f"Target Y: {format_range(report['target_y'])}")
    print(f"Missing images: {report['missing_images']}")
    print()
    print("EE Goal Delta")
    print(f"Samples: {len(ee_goal_distances)}")
    print(f"Mean: {format_number(mean(ee_goal_distances))}")
    print(f"Min: {format_number(min(ee_goal_distances) if ee_goal_distances else None)}")
    print(f"Max: {format_number(max(ee_goal_distances) if ee_goal_distances else None)}")


def main() -> int:
    args = parse_args()
    csv_path = args.csv
    if not csv_path.exists():
        print(f"CSV not found: {csv_path}")
        return 1

    report = analyze(csv_path)
    print_report(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
