# SPDX-FileCopyrightText: Copyright (c) 2021-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Offline analyzer for OpenVLA adapter dry-run CSV logs.
# This intentionally avoids Isaac Sim imports so it can run in normal Python.

from __future__ import annotations

import argparse
import csv
import math
import sys
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable


VLA_ACTION_FIELDS = (
    "vla_dx",
    "vla_dy",
    "vla_dz",
    "vla_droll",
    "vla_dpitch",
    "vla_dyaw",
    "vla_gripper",
)


@dataclass
class AdapterSample:
    run_id: str
    phase_step: str
    global_step: str
    delta_norm: float | None
    error_to_scripted: float | None


@dataclass
class PhaseStats:
    rows: int = 0
    adapter_ready_true: int = 0
    adapter_ready_known: int = 0
    adapter_sample_count: int = 0
    adapter_accepted_true: int = 0
    adapter_accepted_known: int = 0
    adapter_delta_norms: list[float] = field(default_factory=list)
    adapter_errors_to_scripted: list[float] = field(default_factory=list)
    adapter_samples: list[AdapterSample] = field(default_factory=list)
    rejection_reasons: Counter[str] = field(default_factory=Counter)
    vla_queried: int = 0
    vla_successes: int = 0
    vla_errors: Counter[str] = field(default_factory=Counter)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Analyze adapter dry-run calibration.csv logs from vla_pick_place.py "
            "without importing Isaac Sim."
        )
    )
    parser.add_argument(
        "--csv",
        required=True,
        type=Path,
        help="Path to calibration.csv generated by vla_pick_place.py.",
    )
    parser.add_argument(
        "--required-phases",
        default=None,
        help="Comma-separated phase IDs that must be present, for example: 0,1,4.",
    )
    parser.add_argument(
        "--min-adapter-samples-per-phase",
        type=int,
        default=None,
        help="Minimum adapter dry-run samples required for each required/observed phase.",
    )
    parser.add_argument(
        "--min-accepted-rate",
        type=float,
        default=None,
        help=(
            "Minimum adapter acceptance rate per checked phase. Requires logs with "
            "adapter_accepted populated."
        ),
    )
    parser.add_argument(
        "--max-adapter-error-p95",
        type=float,
        default=None,
        help="Maximum p95 adapter_error_to_scripted per checked phase, in meters.",
    )
    parser.add_argument(
        "--max-adapter-error-max",
        type=float,
        default=None,
        help="Maximum worst adapter_error_to_scripted per checked phase, in meters.",
    )
    parser.add_argument(
        "--max-adapter-delta-p95",
        type=float,
        default=None,
        help="Maximum p95 adapter_delta_norm per checked phase, in meters.",
    )
    parser.add_argument(
        "--max-adapter-delta-max",
        type=float,
        default=None,
        help="Maximum worst adapter_delta_norm per checked phase, in meters.",
    )
    parser.add_argument(
        "--worst-rows",
        type=int,
        default=3,
        help="Number of worst adapter rows to print per phase for error and delta norm.",
    )
    parser.add_argument(
        "--top-reasons",
        type=int,
        default=8,
        help="Maximum rejection reasons and VLA errors to print per phase.",
    )
    return parser.parse_args()


def to_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        result = float(text)
    except ValueError:
        return None
    if not math.isfinite(result):
        return None
    return result


def parse_boolish(value: object) -> bool | None:
    if value is None:
        return None
    text = str(value).strip().lower()
    if not text:
        return None
    if text in {"1", "true", "yes", "y"}:
        return True
    if text in {"0", "false", "no", "n"}:
        return False
    return None


def parse_csv_values(raw_value: str | None) -> list[str]:
    if raw_value is None:
        return []
    return [value.strip() for value in raw_value.split(",") if value.strip()]


def vector3(row: dict[str, str], prefix: str) -> tuple[float, float, float] | None:
    values = (
        to_float(row.get(f"{prefix}_x")),
        to_float(row.get(f"{prefix}_y")),
        to_float(row.get(f"{prefix}_z")),
    )
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def norm3(values: tuple[float, float, float]) -> float:
    return math.sqrt(sum(value * value for value in values))


def distance3(left: tuple[float, float, float], right: tuple[float, float, float]) -> float:
    return norm3((left[0] - right[0], left[1] - right[1], left[2] - right[2]))


def percentile(values: list[float], percent: float) -> float | None:
    if not values:
        return None
    if percent <= 0:
        return min(values)
    if percent >= 100:
        return max(values)
    ordered = sorted(values)
    rank = math.ceil((percent / 100.0) * len(ordered))
    index = max(0, min(rank - 1, len(ordered) - 1))
    return ordered[index]


def mean(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def format_number(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.6g}"


def format_rate(numerator: int, denominator: int) -> str:
    if denominator <= 0:
        return "n/a"
    return f"{numerator / denominator:.3f} ({numerator}/{denominator})"


def summarize_counter(counter: Counter[str], limit: int) -> str:
    if not counter:
        return "none"
    items = counter.most_common(max(limit, 0))
    return "; ".join(f"{reason}={count}" for reason, count in items) if items else "none"


def adapter_delta_norm(row: dict[str, str]) -> float | None:
    explicit = to_float(row.get("adapter_delta_norm"))
    if explicit is not None:
        return explicit
    delta = vector3(row, "adapter_delta")
    return norm3(delta) if delta is not None else None


def adapter_error_to_scripted(row: dict[str, str]) -> float | None:
    explicit = to_float(row.get("adapter_error_to_scripted"))
    if explicit is not None:
        return explicit
    adapter_goal = vector3(row, "adapter_goal")
    scripted_goal = vector3(row, "scripted_ee_goal")
    if adapter_goal is None or scripted_goal is None:
        return None
    return distance3(adapter_goal, scripted_goal)


def has_complete_vla_action(row: dict[str, str]) -> bool:
    return all(to_float(row.get(field)) is not None for field in VLA_ACTION_FIELDS)


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def analyze(csv_path: Path) -> tuple[dict[str, PhaseStats], int]:
    rows = load_rows(csv_path)
    phases: dict[str, PhaseStats] = defaultdict(PhaseStats)

    for row in rows:
        phase = (row.get("phase") or "unknown").strip() or "unknown"
        stats = phases[phase]
        stats.rows += 1

        ready = parse_boolish(row.get("adapter_ready"))
        if ready is not None:
            stats.adapter_ready_known += 1
            if ready:
                stats.adapter_ready_true += 1

        delta_norm = adapter_delta_norm(row)
        error_to_scripted = adapter_error_to_scripted(row)
        if delta_norm is not None or error_to_scripted is not None:
            stats.adapter_sample_count += 1
            stats.adapter_samples.append(
                AdapterSample(
                    run_id=(row.get("run_id") or "").strip(),
                    phase_step=(row.get("phase_step") or "").strip(),
                    global_step=(row.get("global_step") or "").strip(),
                    delta_norm=delta_norm,
                    error_to_scripted=error_to_scripted,
                )
            )
        if delta_norm is not None:
            stats.adapter_delta_norms.append(delta_norm)
        if error_to_scripted is not None:
            stats.adapter_errors_to_scripted.append(error_to_scripted)

        accepted = parse_boolish(row.get("adapter_accepted"))
        if accepted is not None:
            stats.adapter_accepted_known += 1
            if accepted:
                stats.adapter_accepted_true += 1

        rejection_reason = (row.get("adapter_rejected_reason") or "").strip()
        if rejection_reason:
            stats.rejection_reasons[rejection_reason] += 1

        queried = parse_boolish(row.get("vla_queried"))
        vla_error = (row.get("vla_error") or "").strip()
        if queried:
            stats.vla_queried += 1
            if has_complete_vla_action(row) and not vla_error:
                stats.vla_successes += 1
            else:
                stats.vla_errors[vla_error or "queried without complete 7D action"] += 1

    return dict(phases), len(rows)


def checked_phases(phases: dict[str, PhaseStats], required: list[str]) -> list[str]:
    if required:
        return required
    return sorted(phase for phase, stats in phases.items() if stats.adapter_sample_count > 0)


def evaluate_gates(args: argparse.Namespace, phases: dict[str, PhaseStats]) -> list[str]:
    failures: list[str] = []
    required = parse_csv_values(args.required_phases)
    phase_ids = checked_phases(phases, required)

    for phase in required:
        if phase not in phases:
            failures.append(f"required phase {phase} is missing")

    if args.min_adapter_samples_per_phase is not None:
        for phase in phase_ids:
            actual = phases.get(phase, PhaseStats()).adapter_sample_count
            if actual < args.min_adapter_samples_per_phase:
                failures.append(
                    f"phase {phase} adapter samples {actual} < {args.min_adapter_samples_per_phase}"
                )

    if args.min_accepted_rate is not None:
        for phase in phase_ids:
            stats = phases.get(phase, PhaseStats())
            if stats.adapter_accepted_known <= 0:
                failures.append(f"phase {phase} accepted rate is n/a")
                continue
            rate = stats.adapter_accepted_true / stats.adapter_accepted_known
            if rate < args.min_accepted_rate:
                failures.append(f"phase {phase} accepted rate {rate:.6g} < {args.min_accepted_rate:.6g}")

    if args.max_adapter_error_p95 is not None:
        for phase in phase_ids:
            p95 = percentile(phases.get(phase, PhaseStats()).adapter_errors_to_scripted, 95)
            if p95 is None:
                failures.append(f"phase {phase} adapter error p95 is n/a")
            elif p95 > args.max_adapter_error_p95:
                failures.append(
                    f"phase {phase} adapter error p95 {p95:.6g} > {args.max_adapter_error_p95:.6g}"
                )

    if args.max_adapter_error_max is not None:
        for phase in phase_ids:
            worst = percentile(phases.get(phase, PhaseStats()).adapter_errors_to_scripted, 100)
            if worst is None:
                failures.append(f"phase {phase} adapter error max is n/a")
            elif worst > args.max_adapter_error_max:
                failures.append(
                    f"phase {phase} adapter error max {worst:.6g} > {args.max_adapter_error_max:.6g}"
                )

    if args.max_adapter_delta_p95 is not None:
        for phase in phase_ids:
            p95 = percentile(phases.get(phase, PhaseStats()).adapter_delta_norms, 95)
            if p95 is None:
                failures.append(f"phase {phase} adapter delta p95 is n/a")
            elif p95 > args.max_adapter_delta_p95:
                failures.append(
                    f"phase {phase} adapter delta p95 {p95:.6g} > {args.max_adapter_delta_p95:.6g}"
                )

    if args.max_adapter_delta_max is not None:
        for phase in phase_ids:
            worst = percentile(phases.get(phase, PhaseStats()).adapter_delta_norms, 100)
            if worst is None:
                failures.append(f"phase {phase} adapter delta max is n/a")
            elif worst > args.max_adapter_delta_max:
                failures.append(
                    f"phase {phase} adapter delta max {worst:.6g} > {args.max_adapter_delta_max:.6g}"
                )

    return failures


def print_metric_block(title: str, values: Iterable[float]) -> None:
    vals = list(values)
    print(
        f"{title}: count={len(vals)} "
        f"mean={format_number(mean(vals))} "
        f"p50={format_number(percentile(vals, 50))} "
        f"p95={format_number(percentile(vals, 95))} "
        f"max={format_number(percentile(vals, 100))}"
    )


def format_sample(sample: AdapterSample) -> str:
    return (
        f"run={sample.run_id or 'n/a'} "
        f"global_step={sample.global_step or 'n/a'} "
        f"phase_step={sample.phase_step or 'n/a'} "
        f"delta={format_number(sample.delta_norm)} "
        f"error={format_number(sample.error_to_scripted)}"
    )


def worst_samples(
    samples: list[AdapterSample],
    attr: str,
    limit: int,
) -> list[AdapterSample]:
    present = [sample for sample in samples if getattr(sample, attr) is not None]
    return sorted(present, key=lambda sample: getattr(sample, attr), reverse=True)[: max(limit, 0)]


def print_report(
    csv_path: Path,
    phases: dict[str, PhaseStats],
    row_count: int,
    top_reasons: int,
    worst_rows: int,
) -> None:
    print("OpenVLA Adapter Dry-Run Analysis")
    print(f"CSV: {csv_path}")
    print(f"Rows: {row_count}")
    print(f"Phases: {', '.join(f'{phase}={stats.rows}' for phase, stats in sorted(phases.items())) or 'none'}")
    print()

    all_delta_norms = [value for stats in phases.values() for value in stats.adapter_delta_norms]
    all_errors = [value for stats in phases.values() for value in stats.adapter_errors_to_scripted]
    print_metric_block("Adapter delta norm overall", all_delta_norms)
    print_metric_block("Adapter error to scripted overall", all_errors)
    print()

    print("Per-Phase Summary")
    for phase, stats in sorted(phases.items()):
        print(f"phase {phase}:")
        print(f"  rows: {stats.rows}")
        print(f"  adapter_ready: {format_rate(stats.adapter_ready_true, stats.adapter_ready_known)}")
        print(f"  adapter_samples: {stats.adapter_sample_count}")
        print(f"  adapter_accepted: {format_rate(stats.adapter_accepted_true, stats.adapter_accepted_known)}")
        print(
            "  adapter_delta_norm: "
            f"count={len(stats.adapter_delta_norms)} "
            f"mean={format_number(mean(stats.adapter_delta_norms))} "
            f"p95={format_number(percentile(stats.adapter_delta_norms, 95))} "
            f"max={format_number(percentile(stats.adapter_delta_norms, 100))}"
        )
        print(
            "  adapter_error_to_scripted: "
            f"count={len(stats.adapter_errors_to_scripted)} "
            f"mean={format_number(mean(stats.adapter_errors_to_scripted))} "
            f"p95={format_number(percentile(stats.adapter_errors_to_scripted, 95))} "
            f"max={format_number(percentile(stats.adapter_errors_to_scripted, 100))}"
        )
        print(f"  rejection_reasons: {summarize_counter(stats.rejection_reasons, top_reasons)}")
        print(f"  vla_successes: {format_rate(stats.vla_successes, stats.vla_queried)}")
        print(f"  vla_errors: {summarize_counter(stats.vla_errors, top_reasons)}")
        error_rows = worst_samples(stats.adapter_samples, "error_to_scripted", worst_rows)
        delta_rows = worst_samples(stats.adapter_samples, "delta_norm", worst_rows)
        if error_rows:
            print("  worst_error_rows:")
            for sample in error_rows:
                print(f"    - {format_sample(sample)}")
        if delta_rows:
            print("  worst_delta_rows:")
            for sample in delta_rows:
                print(f"    - {format_sample(sample)}")


def main() -> int:
    args = parse_args()
    if not args.csv.exists():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        return 2

    phases, row_count = analyze(args.csv)
    print_report(args.csv, phases, row_count, args.top_reasons, args.worst_rows)

    failures = evaluate_gates(args, phases)
    if failures:
        print()
        print("Gate Failures")
        for failure in failures:
            print(f"- {failure}")
        return 1

    if any(
        value is not None
        for value in (
            args.required_phases,
            args.min_adapter_samples_per_phase,
            args.min_accepted_rate,
            args.max_adapter_error_p95,
            args.max_adapter_error_max,
            args.max_adapter_delta_p95,
            args.max_adapter_delta_max,
        )
    ):
        print()
        print("Gate result: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
