# SPDX-FileCopyrightText: Copyright (c) 2021-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Standalone analyzer for OpenVLA Franka calibration CSV logs.
# This intentionally avoids Isaac Sim imports so it can run in normal Python.

from __future__ import annotations

import argparse
import csv
import math
from collections import Counter
from pathlib import Path
from typing import Iterable


VLA_ACTION_FIELDS = [
    "vla_dx",
    "vla_dy",
    "vla_dz",
    "vla_droll",
    "vla_dpitch",
    "vla_dyaw",
    "vla_gripper",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Analyze observer-only OpenVLA Franka calibration CSV logs."
    )
    parser.add_argument(
        "--csv",
        required=True,
        type=Path,
        help="Path to calibration.csv generated by vla_pick_place.py.",
    )
    parser.add_argument("--min-runs", type=int, default=None, help="Minimum unique run count.")
    parser.add_argument("--min-rows", type=int, default=None, help="Minimum CSV row count.")
    parser.add_argument(
        "--min-vla-success-rate",
        type=float,
        default=None,
        help="Minimum successful VLA query rate over queried rows.",
    )
    parser.add_argument(
        "--max-vla-error-rate",
        type=float,
        default=None,
        help="Maximum VLA error rate over queried rows.",
    )
    parser.add_argument(
        "--max-missing-image-rate",
        type=float,
        default=None,
        help="Maximum missing image rate over all rows.",
    )
    parser.add_argument("--min-cube-x-span", type=float, default=None, help="Minimum cube X coverage span.")
    parser.add_argument("--min-cube-y-span", type=float, default=None, help="Minimum cube Y coverage span.")
    parser.add_argument(
        "--min-target-x-span",
        type=float,
        default=None,
        help="Minimum target X coverage span.",
    )
    parser.add_argument(
        "--min-target-y-span",
        type=float,
        default=None,
        help="Minimum target Y coverage span.",
    )
    parser.add_argument(
        "--max-latency-ms",
        type=float,
        default=None,
        help="Maximum observed OpenVLA latency in milliseconds.",
    )
    parser.add_argument(
        "--min-query-successes-total",
        type=int,
        default=None,
        help="Minimum total successful OpenVLA query count.",
    )
    parser.add_argument(
        "--min-query-successes-per-phase",
        type=int,
        default=None,
        help="Minimum successful OpenVLA query count for each required/observed phase.",
    )
    parser.add_argument(
        "--required-phases",
        default=None,
        help="Comma-separated phases that must be present and satisfy per-phase gates, e.g. 0,1,4.",
    )
    parser.add_argument(
        "--min-label-count",
        type=int,
        default=None,
        help="Minimum number of distinct non-empty target labels.",
    )
    parser.add_argument(
        "--min-runs-per-label",
        type=int,
        default=None,
        help="Minimum unique runs for each observed target label.",
    )
    parser.add_argument(
        "--max-vla-latency-p95-ms",
        type=float,
        default=None,
        help="Maximum p95 OpenVLA latency in milliseconds.",
    )
    parser.add_argument(
        "--max-vla-latency-max-ms",
        type=float,
        default=None,
        help="Maximum max OpenVLA latency in milliseconds.",
    )
    parser.add_argument(
        "--max-empty-camera-frames",
        type=int,
        default=None,
        help="Maximum rows whose VLA error reports an empty camera frame.",
    )
    parser.add_argument(
        "--final-distance-threshold",
        type=float,
        default=0.08,
        help="Final cube-to-target XY distance threshold for success-like run counts.",
    )
    parser.add_argument(
        "--min-success-like-runs",
        type=int,
        default=None,
        help="Minimum runs whose final cube-to-target XY distance is within --final-distance-threshold.",
    )
    parser.add_argument(
        "--min-final-success-rate",
        type=float,
        default=None,
        help="Minimum fraction of runs within --final-distance-threshold at final placement.",
    )
    parser.add_argument(
        "--max-final-distance",
        type=float,
        default=None,
        help="Maximum allowed final cube-to-target XY distance across runs.",
    )
    parser.add_argument(
        "--show-runs",
        action="store_true",
        help="Print per-run initial/final cube and target diagnostics.",
    )
    parser.add_argument(
        "--max-runs-shown",
        type=int,
        default=20,
        help="Maximum run summaries to print when --show-runs is set.",
    )
    return parser.parse_args()


def to_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        result = float(text)
    except ValueError:
        return None
    if not math.isfinite(result):
        return None
    return result


def parse_boolish(value: object) -> bool:
    if value is None:
        return False
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


def format_range(values: Iterable[float]) -> str:
    vals = list(values)
    if not vals:
        return "n/a"
    return f"{min(vals):.6g} .. {max(vals):.6g}"


def format_number(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.6g}"


def format_xy(value: tuple[float, float] | None) -> str:
    if value is None:
        return "(n/a, n/a)"
    return f"({value[0]:.6g}, {value[1]:.6g})"


def mean(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def percentile(values: list[float], percent: float) -> float | None:
    if not values:
        return None
    if percent <= 0:
        return min(values)
    if percent >= 100:
        return max(values)

    ordered = sorted(values)
    rank = math.ceil((percent / 100.0) * len(ordered))
    index = max(0, min(rank - 1, len(ordered) - 1))
    return ordered[index]


def span(values: list[float]) -> float | None:
    if not values:
        return None
    return max(values) - min(values)


def vector3(row: dict[str, str], prefix: str) -> tuple[float, float, float] | None:
    values = (
        to_float(row.get(f"{prefix}_x")),
        to_float(row.get(f"{prefix}_y")),
        to_float(row.get(f"{prefix}_z")),
    )
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def distance_3d(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return math.sqrt(sum((left - right) ** 2 for left, right in zip(a, b)))


def distance_2d(a: tuple[float, float], b: tuple[float, float]) -> float:
    return math.sqrt(sum((left - right) ** 2 for left, right in zip(a, b)))


def is_missing_image(row: dict[str, str], csv_path: Path) -> bool:
    raw_path = (row.get("image_path") or "").strip()
    if not raw_path:
        return True

    image_path = Path(raw_path)
    if not image_path.is_absolute():
        image_path = csv_path.parent / image_path
    return not image_path.exists()


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def parse_csv_values(raw_value: str | None) -> list[str]:
    if not raw_value:
        return []
    return [value.strip() for value in raw_value.split(",") if value.strip()]


def is_vla_success(row: dict[str, str]) -> bool:
    action = [to_float(row.get(field)) for field in VLA_ACTION_FIELDS]
    has_error = bool((row.get("vla_error") or "").strip())
    return all(value is not None for value in action) and not has_error


def row_xy(row: dict[str, str], x_field: str, y_field: str) -> tuple[float, float] | None:
    x_value = to_float(row.get(x_field))
    y_value = to_float(row.get(y_field))
    if x_value is None or y_value is None:
        return None
    return (x_value, y_value)


def build_run_summaries(
    rows: list[dict[str, str]], final_distance_threshold: float
) -> list[dict[str, object]]:
    rows_by_run: dict[str, list[dict[str, str]]] = {}
    for index, row in enumerate(rows):
        run_id = (row.get("run_id") or "").strip() or f"row_{index}"
        rows_by_run.setdefault(run_id, []).append(row)

    summaries: list[dict[str, object]] = []
    for run_id, run_rows in rows_by_run.items():
        first_row = run_rows[0]
        last_row = run_rows[-1]
        initial_cube_xy = row_xy(first_row, "cube_x", "cube_y")
        target_xy = row_xy(first_row, "target_x", "target_y")
        final_cube_xy = row_xy(last_row, "cube_x", "cube_y")

        final_distance = None
        success_like = False
        if final_cube_xy is not None and target_xy is not None:
            final_distance = distance_2d(final_cube_xy, target_xy)
            success_like = final_distance <= final_distance_threshold

        label = (first_row.get("target_label") or "").strip()
        if not label:
            label = "n/a"

        summaries.append(
            {
                "run_id": run_id,
                "target_label": label,
                "initial_cube_xy": initial_cube_xy,
                "target_xy": target_xy,
                "final_cube_xy": final_cube_xy,
                "final_distance_to_target": final_distance,
                "success_like": success_like,
                "row_count": len(run_rows),
                "query_successes": sum(
                    1
                    for row in run_rows
                    if parse_boolish(row.get("vla_queried")) and is_vla_success(row)
                ),
            }
        )

    return summaries


def analyze(csv_path: Path, final_distance_threshold: float) -> dict[str, object]:
    rows = load_rows(csv_path)
    run_summaries = build_run_summaries(rows, final_distance_threshold)

    run_ids = {row.get("run_id", "") for row in rows if row.get("run_id", "") != ""}
    phases = Counter(row.get("phase", "unknown") or "unknown" for row in rows)

    queried_rows = [row for row in rows if parse_boolish(row.get("vla_queried"))]
    vla_error_count = sum(1 for row in queried_rows if (row.get("vla_error") or "").strip())
    empty_camera_frames = sum(
        1
        for row in rows
        if "empty camera frame" in (row.get("vla_error") or "").strip().lower()
    )

    vla_success_count = 0
    vla_incomplete_count = 0
    query_successes_by_phase: Counter[str] = Counter()
    for row in queried_rows:
        has_error = bool((row.get("vla_error") or "").strip())
        if is_vla_success(row):
            vla_success_count += 1
            query_successes_by_phase[row.get("phase", "unknown") or "unknown"] += 1
        elif not has_error:
            vla_incomplete_count += 1

    target_labels = Counter(
        (row.get("target_label") or "").strip()
        for row in rows
        if (row.get("target_label") or "").strip()
    )
    runs_by_label: dict[str, set[str]] = {}
    for row in rows:
        label = (row.get("target_label") or "").strip()
        run_id = (row.get("run_id") or "").strip()
        if label and run_id:
            runs_by_label.setdefault(label, set()).add(run_id)
    run_counts_by_label = Counter({label: len(run_ids) for label, run_ids in runs_by_label.items()})

    cube_x = [value for row in rows if (value := to_float(row.get("cube_x"))) is not None]
    cube_y = [value for row in rows if (value := to_float(row.get("cube_y"))) is not None]
    target_x = [value for row in rows if (value := to_float(row.get("target_x"))) is not None]
    target_y = [value for row in rows if (value := to_float(row.get("target_y"))) is not None]

    missing_images = sum(1 for row in rows if is_missing_image(row, csv_path))
    latencies_ms = [value for row in rows if (value := to_float(row.get("vla_latency_ms"))) is not None]

    ee_goal_distances: list[float] = []
    for row in rows:
        ee_pos = vector3(row, "ee_pos")
        scripted_goal = vector3(row, "scripted_ee_goal")
        if ee_pos is not None and scripted_goal is not None:
            ee_goal_distances.append(distance_3d(ee_pos, scripted_goal))

    return {
        "csv_path": csv_path,
        "row_count": len(rows),
        "run_count": len(run_ids),
        "run_summaries": run_summaries,
        "final_distance_threshold": final_distance_threshold,
        "phases": phases,
        "vla_queried_count": len(queried_rows),
        "vla_success_count": vla_success_count,
        "vla_error_count": vla_error_count,
        "vla_incomplete_count": vla_incomplete_count,
        "query_successes_by_phase": query_successes_by_phase,
        "target_labels": target_labels,
        "run_counts_by_label": run_counts_by_label,
        "empty_camera_frames": empty_camera_frames,
        "cube_x": cube_x,
        "cube_y": cube_y,
        "target_x": target_x,
        "target_y": target_y,
        "missing_images": missing_images,
        "latencies_ms": latencies_ms,
        "ee_goal_distances": ee_goal_distances,
    }


def rate(numerator: int, denominator: int) -> float | None:
    if denominator <= 0:
        return None
    return numerator / denominator


def evaluate_gates(args: argparse.Namespace, report: dict[str, object]) -> list[dict[str, object]]:
    row_count = int(report["row_count"])
    run_count = int(report["run_count"])
    queried_count = int(report["vla_queried_count"])
    success_count = int(report["vla_success_count"])
    error_count = int(report["vla_error_count"])
    missing_images = int(report["missing_images"])
    empty_camera_frames = int(report["empty_camera_frames"])
    latencies_ms = report["latencies_ms"]
    assert isinstance(latencies_ms, list)
    query_successes_by_phase = report["query_successes_by_phase"]
    assert isinstance(query_successes_by_phase, Counter)
    target_labels = report["target_labels"]
    assert isinstance(target_labels, Counter)
    run_counts_by_label = report["run_counts_by_label"]
    assert isinstance(run_counts_by_label, Counter)
    run_summaries = report["run_summaries"]
    assert isinstance(run_summaries, list)

    gates: list[dict[str, object]] = []

    def add_gate(name: str, actual: float | int | None, expected: str, passed: bool) -> None:
        gates.append(
            {
                "name": name,
                "actual": actual,
                "expected": expected,
                "passed": passed,
            }
        )

    if args.min_runs is not None:
        add_gate("Runs", run_count, f">= {args.min_runs}", run_count >= args.min_runs)
    if args.min_rows is not None:
        add_gate("Rows", row_count, f">= {args.min_rows}", row_count >= args.min_rows)
    if args.min_vla_success_rate is not None:
        actual = rate(success_count, queried_count)
        add_gate(
            "VLA success rate",
            actual,
            f">= {args.min_vla_success_rate:.6g}",
            actual is not None and actual >= args.min_vla_success_rate,
        )
    if args.max_vla_error_rate is not None:
        actual = rate(error_count, queried_count)
        add_gate(
            "VLA error rate",
            actual,
            f"<= {args.max_vla_error_rate:.6g}",
            actual is not None and actual <= args.max_vla_error_rate,
        )
    if args.max_missing_image_rate is not None:
        actual = rate(missing_images, row_count)
        add_gate(
            "Missing image rate",
            actual,
            f"<= {args.max_missing_image_rate:.6g}",
            actual is not None and actual <= args.max_missing_image_rate,
        )

    span_checks = [
        ("Cube X span", report["cube_x"], args.min_cube_x_span),
        ("Cube Y span", report["cube_y"], args.min_cube_y_span),
        ("Target X span", report["target_x"], args.min_target_x_span),
        ("Target Y span", report["target_y"], args.min_target_y_span),
    ]
    for name, values, minimum in span_checks:
        if minimum is None:
            continue
        assert isinstance(values, list)
        actual = span(values)
        add_gate(name, actual, f">= {minimum:.6g}", actual is not None and actual >= minimum)

    if args.max_latency_ms is not None:
        actual = max(latencies_ms) if latencies_ms else None
        add_gate(
            "Max latency ms",
            actual,
            f"<= {args.max_latency_ms:.6g}",
            actual is not None and actual <= args.max_latency_ms,
        )

    if args.min_query_successes_total is not None:
        add_gate(
            "Query successes total",
            success_count,
            f">= {args.min_query_successes_total}",
            success_count >= args.min_query_successes_total,
        )

    required_phases = parse_csv_values(args.required_phases)
    for phase in required_phases:
        actual = query_successes_by_phase.get(phase, 0)
        add_gate(f"Required phase {phase} query successes", actual, ">= 1", actual >= 1)

    if args.min_query_successes_per_phase is not None:
        phases_to_check = required_phases or sorted(str(phase) for phase in query_successes_by_phase.keys())
        if not phases_to_check:
            add_gate(
                "Query successes per phase",
                None,
                f">= {args.min_query_successes_per_phase}",
                False,
            )
        for phase in phases_to_check:
            actual = query_successes_by_phase.get(phase, 0)
            add_gate(
                f"Phase {phase} query successes",
                actual,
                f">= {args.min_query_successes_per_phase}",
                actual >= args.min_query_successes_per_phase,
            )

    if args.min_label_count is not None:
        actual = len(target_labels)
        add_gate("Target label count", actual, f">= {args.min_label_count}", actual >= args.min_label_count)

    if args.min_runs_per_label is not None:
        if not run_counts_by_label:
            add_gate("Runs per target label", None, f">= {args.min_runs_per_label}", False)
        for label, actual in sorted(run_counts_by_label.items()):
            add_gate(
                f"Runs for label '{label}'",
                actual,
                f">= {args.min_runs_per_label}",
                actual >= args.min_runs_per_label,
            )

    if args.max_vla_latency_p95_ms is not None:
        actual = percentile(latencies_ms, 95)
        add_gate(
            "VLA latency p95 ms",
            actual,
            f"<= {args.max_vla_latency_p95_ms:.6g}",
            actual is not None and actual <= args.max_vla_latency_p95_ms,
        )

    if args.max_vla_latency_max_ms is not None:
        actual = max(latencies_ms) if latencies_ms else None
        add_gate(
            "VLA latency max ms",
            actual,
            f"<= {args.max_vla_latency_max_ms:.6g}",
            actual is not None and actual <= args.max_vla_latency_max_ms,
        )

    if args.max_empty_camera_frames is not None:
        add_gate(
            "Empty camera frames",
            empty_camera_frames,
            f"<= {args.max_empty_camera_frames}",
            empty_camera_frames <= args.max_empty_camera_frames,
        )

    success_like_runs = sum(1 for summary in run_summaries if summary.get("success_like"))
    final_distances = [
        summary["final_distance_to_target"]
        for summary in run_summaries
        if summary.get("final_distance_to_target") is not None
    ]

    if args.min_success_like_runs is not None:
        add_gate(
            "Success-like runs",
            success_like_runs,
            f">= {args.min_success_like_runs}",
            success_like_runs >= args.min_success_like_runs,
        )

    if args.min_final_success_rate is not None:
        actual = rate(success_like_runs, len(run_summaries))
        add_gate(
            "Final success rate",
            actual,
            f">= {args.min_final_success_rate:.6g}",
            actual is not None and actual >= args.min_final_success_rate,
        )

    if args.max_final_distance is not None:
        actual = max(final_distances) if final_distances else None
        add_gate(
            "Final distance max",
            actual,
            f"<= {args.max_final_distance:.6g}",
            actual is not None and actual <= args.max_final_distance,
        )

    return gates


def format_gate_actual(value: object) -> str:
    if isinstance(value, float):
        return format_number(value)
    if value is None:
        return "n/a"
    return str(value)


def print_quality_gates(gates: list[dict[str, object]]) -> None:
    if not gates:
        return

    print()
    print("Quality Gates")
    for gate in gates:
        status = "PASS" if gate["passed"] else "FAIL"
        print(
            f"{gate['name']} {gate['expected']}: {status} "
            f"(actual {format_gate_actual(gate['actual'])})"
        )

    overall = "PASS" if all(bool(gate["passed"]) for gate in gates) else "FAIL"
    print(f"Overall: {overall}")


def print_report(report: dict[str, object], show_runs: bool, max_runs_shown: int) -> None:
    phases = report["phases"]
    assert isinstance(phases, Counter)

    ee_goal_distances = report["ee_goal_distances"]
    assert isinstance(ee_goal_distances, list)
    latencies_ms = report["latencies_ms"]
    assert isinstance(latencies_ms, list)
    query_successes_by_phase = report["query_successes_by_phase"]
    assert isinstance(query_successes_by_phase, Counter)
    target_labels = report["target_labels"]
    assert isinstance(target_labels, Counter)
    run_counts_by_label = report["run_counts_by_label"]
    assert isinstance(run_counts_by_label, Counter)
    run_summaries = report["run_summaries"]
    assert isinstance(run_summaries, list)

    phase_report = ", ".join(f"{phase}={count}" for phase, count in sorted(phases.items()))
    if not phase_report:
        phase_report = "n/a"

    print("VLA Calibration Report")
    print(f"CSV: {report['csv_path']}")
    print(f"Rows: {report['row_count']}")
    print(f"Runs: {report['run_count']}")
    print(f"Phases: {phase_report}")
    print()
    print("VLA")
    print(f"Queried: {report['vla_queried_count']}")
    print(f"Success: {report['vla_success_count']}")
    print(f"Errors: {report['vla_error_count']}")
    print(f"Incomplete actions: {report['vla_incomplete_count']}")
    print(f"Latency samples: {len(latencies_ms)}")
    print(f"Latency mean ms: {format_number(mean(latencies_ms))}")
    print(f"Latency p50 ms: {format_number(percentile(latencies_ms, 50))}")
    print(f"Latency p90 ms: {format_number(percentile(latencies_ms, 90))}")
    print(f"Latency p95 ms: {format_number(percentile(latencies_ms, 95))}")
    print(f"Latency max ms: {format_number(max(latencies_ms) if latencies_ms else None)}")
    print(f"Empty camera frames: {report['empty_camera_frames']}")
    print()
    print("Query Successes By Phase")
    if query_successes_by_phase:
        for phase, count in sorted(query_successes_by_phase.items()):
            print(f"phase {phase}: {count}")
    else:
        print("n/a")
    print()
    print("Target Labels")
    if target_labels:
        for label, row_count in sorted(target_labels.items()):
            run_count = run_counts_by_label.get(label, 0)
            print(f"{label}: {run_count} runs, {row_count} rows")
    else:
        print("n/a")
    print()
    print("Scene Coverage")
    print(f"Cube X: {format_range(report['cube_x'])}")
    print(f"Cube Y: {format_range(report['cube_y'])}")
    print(f"Target X: {format_range(report['target_x'])}")
    print(f"Target Y: {format_range(report['target_y'])}")
    print(f"Missing images: {report['missing_images']}")
    print()
    print("Run-Level Coverage")
    initial_cube_x = [
        summary["initial_cube_xy"][0]
        for summary in run_summaries
        if summary.get("initial_cube_xy") is not None
    ]
    initial_cube_y = [
        summary["initial_cube_xy"][1]
        for summary in run_summaries
        if summary.get("initial_cube_xy") is not None
    ]
    run_target_x = [
        summary["target_xy"][0]
        for summary in run_summaries
        if summary.get("target_xy") is not None
    ]
    run_target_y = [
        summary["target_xy"][1]
        for summary in run_summaries
        if summary.get("target_xy") is not None
    ]
    final_distances = [
        summary["final_distance_to_target"]
        for summary in run_summaries
        if summary.get("final_distance_to_target") is not None
    ]
    success_like_count = sum(1 for summary in run_summaries if summary.get("success_like"))
    print(f"Initial cube X: {format_range(initial_cube_x)}")
    print(f"Initial cube Y: {format_range(initial_cube_y)}")
    print(f"Target X: {format_range(run_target_x)}")
    print(f"Target Y: {format_range(run_target_y)}")
    print(f"Final distance threshold: {format_number(report['final_distance_threshold'])}")
    print(f"Success-like runs: {success_like_count} / {len(run_summaries)}")
    print(f"Final distance mean: {format_number(mean(final_distances))}")
    print(f"Final distance max: {format_number(max(final_distances) if final_distances else None)}")
    if show_runs:
        print()
        print("Run Summary")
        shown_count = max(0, max_runs_shown)
        for summary in run_summaries[:shown_count]:
            print(
                f"{summary['run_id']} label={summary['target_label']} "
                f"initial_cube={format_xy(summary['initial_cube_xy'])} "
                f"target={format_xy(summary['target_xy'])} "
                f"final_cube={format_xy(summary['final_cube_xy'])} "
                f"final_distance_to_target={format_number(summary['final_distance_to_target'])} "
                f"rows={summary['row_count']} "
                f"query_successes={summary['query_successes']}"
            )
        if len(run_summaries) > shown_count:
            print(f"... {len(run_summaries) - shown_count} more runs not shown")
    print()
    print("EE Goal Delta")
    print(f"Samples: {len(ee_goal_distances)}")
    print(f"Mean: {format_number(mean(ee_goal_distances))}")
    print(f"Min: {format_number(min(ee_goal_distances) if ee_goal_distances else None)}")
    print(f"Max: {format_number(max(ee_goal_distances) if ee_goal_distances else None)}")


def main() -> int:
    args = parse_args()
    csv_path = args.csv
    if not csv_path.exists():
        print(f"CSV not found: {csv_path}")
        return 1

    report = analyze(csv_path, args.final_distance_threshold)
    print_report(report, args.show_runs, args.max_runs_shown)
    gates = evaluate_gates(args, report)
    print_quality_gates(gates)
    if gates and not all(bool(gate["passed"]) for gate in gates):
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
