# SPDX-FileCopyrightText: Copyright (c) 2021-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Fit offline OpenVLA xyz-to-waypoint adapters from calibration CSV logs.
# This intentionally avoids Isaac Sim imports and never controls the robot.

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


AXES = ("x", "y", "z")
DEFAULT_PHASES = ("0", "1", "4")
XYZ_ACTION_FIELDS = ("vla_dx", "vla_dy", "vla_dz")


@dataclass(frozen=True)
class Sample:
    run_id: str
    phase: str
    action_xyz: tuple[float, float, float]
    ee_pos: tuple[float, float, float]
    scripted_goal: tuple[float, float, float]

    @property
    def desired_delta(self) -> tuple[float, float, float]:
        return tuple(goal - pos for goal, pos in zip(self.scripted_goal, self.ee_pos))  # type: ignore[return-value]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fit offline affine adapters from OpenVLA xyz actions to scripted Franka waypoint deltas."
    )
    parser.add_argument("--csv", required=True, type=Path, help="Calibration CSV generated by vla_pick_place.py.")
    parser.add_argument(
        "--phase",
        action="append",
        default=[],
        help="Phase filter. Use 'all', repeat values, or comma-separate values. Default: 0,1,4.",
    )
    parser.add_argument(
        "--holdout-fraction",
        type=float,
        default=0.3,
        help="Fraction of sorted run IDs used as test runs.",
    )
    parser.add_argument("--ridge", type=float, default=1e-6, help="Small L2 regularization for linear solve.")
    parser.add_argument("--min-train-samples", type=int, default=20)
    parser.add_argument("--min-test-samples", type=int, default=10)
    parser.add_argument(
        "--compare-raw-scale",
        type=float,
        default=1.0,
        help="Scale for the raw clipped VLA baseline.",
    )
    parser.add_argument("--clip", type=float, default=0.03, help="Clip raw VLA xyz deltas for raw baseline.")
    parser.add_argument(
        "--min-test-improvement",
        type=float,
        default=10.0,
        help="Minimum held-out improvement percentage before a fitted phase is marked ready.",
    )
    parser.add_argument(
        "--write-config",
        type=Path,
        default=None,
        help="Optional JSON path for fitted coefficients and readiness metadata.",
    )
    return parser.parse_args()


def to_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        result = float(text)
    except ValueError:
        return None
    if not math.isfinite(result):
        return None
    return result


def parse_phase_filters(raw_filters: Iterable[str]) -> set[str]:
    if not raw_filters:
        return set(DEFAULT_PHASES)

    phases: set[str] = set()
    for raw_filter in raw_filters:
        for phase in str(raw_filter).split(","):
            phase = phase.strip().lower()
            if not phase:
                continue
            if phase == "all":
                return set()
            phases.add(phase)
    return phases


def vector3(row: dict[str, str], prefix: str) -> tuple[float, float, float] | None:
    values = (
        to_float(row.get(f"{prefix}_x")),
        to_float(row.get(f"{prefix}_y")),
        to_float(row.get(f"{prefix}_z")),
    )
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def vla_xyz(row: dict[str, str]) -> tuple[float, float, float] | None:
    values = tuple(to_float(row.get(field)) for field in XYZ_ACTION_FIELDS)
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def collect_samples(rows: list[dict[str, str]], phases: set[str]) -> list[Sample]:
    samples: list[Sample] = []
    for row in rows:
        phase = (row.get("phase") or "").strip()
        if phases and phase not in phases:
            continue
        if (row.get("vla_error") or "").strip():
            continue

        action_xyz = vla_xyz(row)
        ee_pos = vector3(row, "ee_pos")
        scripted_goal = vector3(row, "scripted_ee_goal")
        if action_xyz is None or ee_pos is None or scripted_goal is None:
            continue

        run_id = (row.get("run_id") or "").strip()
        samples.append(
            Sample(
                run_id=run_id,
                phase=phase,
                action_xyz=action_xyz,
                ee_pos=ee_pos,
                scripted_goal=scripted_goal,
            )
        )
    return samples


def distance_3d(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return math.sqrt(sum((left - right) ** 2 for left, right in zip(a, b)))


def mean(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def fmt(value: float | int | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.6g}"


def pct(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.2f}%"


def clip_value(value: float, limit: float) -> float:
    return max(-limit, min(limit, value))


def raw_predicted_goal(sample: Sample, scale: float, clip: float) -> tuple[float, float, float]:
    clipped = tuple(clip_value(value, clip) for value in sample.action_xyz)
    return tuple(pos + scale * delta for pos, delta in zip(sample.ee_pos, clipped))  # type: ignore[return-value]


def feature_vector(sample: Sample) -> list[float]:
    return [1.0, sample.action_xyz[0], sample.action_xyz[1], sample.action_xyz[2]]


def solve_linear_system(matrix: list[list[float]], values: list[float]) -> list[float] | None:
    n = len(values)
    augmented = [row[:] + [value] for row, value in zip(matrix, values)]

    for column in range(n):
        pivot = max(range(column, n), key=lambda row: abs(augmented[row][column]))
        if abs(augmented[pivot][column]) < 1e-12:
            return None
        if pivot != column:
            augmented[column], augmented[pivot] = augmented[pivot], augmented[column]

        pivot_value = augmented[column][column]
        for col in range(column, n + 1):
            augmented[column][col] /= pivot_value

        for row in range(n):
            if row == column:
                continue
            factor = augmented[row][column]
            for col in range(column, n + 1):
                augmented[row][col] -= factor * augmented[column][col]

    return [augmented[row][n] for row in range(n)]


def fit_affine_adapter(samples: list[Sample], ridge: float) -> list[list[float]] | None:
    # Fits desired_delta_axis = b + wx*vla_dx + wy*vla_dy + wz*vla_dz.
    feature_count = 4
    xtx = [[0.0 for _ in range(feature_count)] for _ in range(feature_count)]
    xty = [[0.0 for _ in AXES] for _ in range(feature_count)]

    for sample in samples:
        features = feature_vector(sample)
        desired = sample.desired_delta
        for i in range(feature_count):
            for j in range(feature_count):
                xtx[i][j] += features[i] * features[j]
            for axis_index in range(3):
                xty[i][axis_index] += features[i] * desired[axis_index]

    for i in range(feature_count):
        xtx[i][i] += ridge

    coefficients: list[list[float]] = []
    for axis_index in range(3):
        solution = solve_linear_system(xtx, [xty[row][axis_index] for row in range(feature_count)])
        if solution is None:
            return None
        coefficients.append(solution)
    return coefficients


def affine_predicted_goal(sample: Sample, coefficients: list[list[float]]) -> tuple[float, float, float]:
    features = feature_vector(sample)
    predicted_delta = tuple(sum(coef * value for coef, value in zip(axis_coeffs, features)) for axis_coeffs in coefficients)
    return tuple(pos + delta for pos, delta in zip(sample.ee_pos, predicted_delta))  # type: ignore[return-value]


def split_by_run(samples: list[Sample], holdout_fraction: float) -> tuple[list[Sample], list[Sample]]:
    run_ids = sorted({sample.run_id for sample in samples})
    if len(run_ids) <= 1:
        return samples, []

    test_count = max(1, round(len(run_ids) * holdout_fraction))
    test_count = min(test_count, len(run_ids) - 1)
    test_runs = set(run_ids[-test_count:])
    train = [sample for sample in samples if sample.run_id not in test_runs]
    test = [sample for sample in samples if sample.run_id in test_runs]
    return train, test


def evaluate(samples: list[Sample], coefficients: list[list[float]], raw_scale: float, clip: float) -> dict[str, float | int | None]:
    baseline_distances: list[float] = []
    raw_distances: list[float] = []
    affine_distances: list[float] = []

    for sample in samples:
        baseline_distances.append(distance_3d(sample.ee_pos, sample.scripted_goal))
        raw_distances.append(distance_3d(raw_predicted_goal(sample, raw_scale, clip), sample.scripted_goal))
        affine_distances.append(distance_3d(affine_predicted_goal(sample, coefficients), sample.scripted_goal))

    baseline_mean = mean(baseline_distances)
    raw_mean = mean(raw_distances)
    affine_mean = mean(affine_distances)

    affine_improvement = None
    raw_improvement = None
    if baseline_mean is not None and baseline_mean > 0:
        if raw_mean is not None:
            raw_improvement = 100.0 * (baseline_mean - raw_mean) / baseline_mean
        if affine_mean is not None:
            affine_improvement = 100.0 * (baseline_mean - affine_mean) / baseline_mean

    return {
        "samples": len(samples),
        "baseline_mean": baseline_mean,
        "raw_mean": raw_mean,
        "raw_improvement": raw_improvement,
        "affine_mean": affine_mean,
        "affine_improvement": affine_improvement,
    }


def sorted_phases(phases: Iterable[str]) -> list[str]:
    return sorted(phases, key=lambda value: (0, int(value)) if value.isdigit() else (1, value))


def print_coefficients(coefficients: list[list[float]]) -> None:
    print("Affine coefficients: desired_delta_axis = b + wx*vla_dx + wy*vla_dy + wz*vla_dz")
    print("axis       b        wx        wy        wz")
    for axis, axis_coeffs in zip(AXES, coefficients):
        print(
            f"{axis:<4} "
            f"{fmt(axis_coeffs[0]):>8} "
            f"{fmt(axis_coeffs[1]):>9} "
            f"{fmt(axis_coeffs[2]):>9} "
            f"{fmt(axis_coeffs[3]):>9}"
        )


def print_eval(label: str, metrics: dict[str, float | int | None]) -> None:
    print(label)
    print(f"samples: {metrics['samples']}")
    print(f"baseline mean: {fmt(metrics['baseline_mean'])}")
    print(f"raw clipped mean: {fmt(metrics['raw_mean'])} ({pct(metrics['raw_improvement'])})")
    print(f"affine mean: {fmt(metrics['affine_mean'])} ({pct(metrics['affine_improvement'])})")


def phase_report(phase: str, samples: list[Sample], args: argparse.Namespace) -> tuple[bool, dict[str, object]]:
    train, test = split_by_run(samples, args.holdout_fraction)
    result: dict[str, object] = {
        "phase": phase,
        "total_samples": len(samples),
        "train_samples": len(train),
        "test_samples": len(test),
        "ready_for_control": False,
        "status": "not_evaluated",
    }

    print()
    print(f"Phase {phase}")
    print(f"total samples: {len(samples)}")
    print(f"train samples: {len(train)}")
    print(f"test samples: {len(test)}")

    if len(train) < args.min_train_samples:
        print(f"status: LOW TRAIN SAMPLE (< {args.min_train_samples})")
        result["status"] = "low_train_sample"
        return False, result
    if len(test) < args.min_test_samples:
        print(f"status: LOW TEST SAMPLE (< {args.min_test_samples})")
        result["status"] = "low_test_sample"
        return False, result

    coefficients = fit_affine_adapter(train, args.ridge)
    if coefficients is None:
        print("status: FIT FAILED")
        result["status"] = "fit_failed"
        return False, result

    train_metrics = evaluate(train, coefficients, args.compare_raw_scale, args.clip)
    test_metrics = evaluate(test, coefficients, args.compare_raw_scale, args.clip)
    test_improvement = test_metrics["affine_improvement"]
    ready = isinstance(test_improvement, float) and test_improvement >= args.min_test_improvement

    result.update(
        {
            "status": "fit_ok",
            "ready_for_control": ready,
            "coefficients": {
                axis: {
                    "bias": axis_coeffs[0],
                    "vla_dx": axis_coeffs[1],
                    "vla_dy": axis_coeffs[2],
                    "vla_dz": axis_coeffs[3],
                }
                for axis, axis_coeffs in zip(AXES, coefficients)
            },
            "train": train_metrics,
            "test": test_metrics,
        }
    )

    print("status: FIT OK")
    print(f"ready for control: {'YES' if ready else 'NO'}")
    print_coefficients(coefficients)
    print_eval("Train", train_metrics)
    print_eval("Test", test_metrics)
    return True, result


def main() -> int:
    args = parse_args()
    if not args.csv.exists():
        print(f"CSV not found: {args.csv}")
        return 1
    if not (0.0 <= args.holdout_fraction < 1.0):
        print("--holdout-fraction must be in [0, 1)")
        return 1
    if args.ridge < 0:
        print("--ridge must be non-negative")
        return 1
    if args.clip < 0:
        print("--clip must be non-negative")
        return 1
    if args.min_test_improvement < 0:
        print("--min-test-improvement must be non-negative")
        return 1

    rows = load_rows(args.csv)
    selected_phases = parse_phase_filters(args.phase)
    samples = collect_samples(rows, selected_phases)
    phases = sorted_phases({sample.phase for sample in samples})

    print("OpenVLA Affine Adapter Fit Report")
    print(f"CSV: {args.csv}")
    print(f"usable samples: {len(samples)}")
    print(f"phases: {','.join(phases) if phases else 'none'}")
    print(f"holdout fraction: {fmt(args.holdout_fraction)}")
    print(f"ridge: {fmt(args.ridge)}")

    if not samples:
        return 2

    any_fit = False
    phase_results: list[dict[str, object]] = []
    for phase in phases:
        phase_samples = [sample for sample in samples if sample.phase == phase]
        fit_ok, result = phase_report(phase, phase_samples, args)
        phase_results.append(result)
        any_fit = fit_ok or any_fit

    if args.write_config is not None:
        config = {
            "source_csv": str(args.csv),
            "adapter_type": "affine_vla_xyz_to_desired_delta",
            "feature_order": ["bias", "vla_dx", "vla_dy", "vla_dz"],
            "holdout_fraction": args.holdout_fraction,
            "ridge": args.ridge,
            "min_test_improvement": args.min_test_improvement,
            "phases": phase_results,
        }
        args.write_config.parent.mkdir(parents=True, exist_ok=True)
        args.write_config.write_text(json.dumps(config, indent=2), encoding="utf-8")
        print()
        print(f"Config written to: {args.write_config}")

    return 0 if any_fit else 2


if __name__ == "__main__":
    raise SystemExit(main())
