# SPDX-FileCopyrightText: Copyright (c) 2021-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Offline adapter report for OpenVLA Franka calibration CSV logs.
# This intentionally avoids Isaac Sim imports so it can run in normal Python.

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Iterable


XYZ_ACTION_FIELDS = ["vla_dx", "vla_dy", "vla_dz"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Report how a simple VLA xyz action adapter compares with scripted Franka goals."
    )
    parser.add_argument(
        "--csv",
        required=True,
        type=Path,
        help="Path to calibration.csv generated by vla_pick_place.py.",
    )
    parser.add_argument(
        "--phase",
        action="append",
        default=[],
        help="Optional phase filter. Can be repeated or comma-separated, e.g. --phase 0,1 --phase 4.",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="Scale applied to clipped VLA xyz deltas.",
    )
    parser.add_argument(
        "--clip",
        type=float,
        default=0.03,
        help="Symmetric per-axis clip applied to raw VLA xyz deltas before scaling.",
    )
    parser.add_argument(
        "--grid-search-scales",
        default="",
        help="Optional comma-separated scale values to evaluate with the same clip.",
    )
    parser.add_argument(
        "--min-samples",
        type=int,
        default=5,
        help="Minimum usable rows before interpreting the adapter comparison as meaningful.",
    )
    return parser.parse_args()


def to_float(value: object) -> float | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        result = float(text)
    except ValueError:
        return None
    if not math.isfinite(result):
        return None
    return result


def parse_phase_filters(raw_filters: Iterable[str]) -> set[str]:
    phases: set[str] = set()
    for raw_filter in raw_filters:
        for phase in str(raw_filter).split(","):
            phase = phase.strip()
            if phase:
                phases.add(phase)
    return phases


def parse_scales(raw_scales: str) -> list[float]:
    if not raw_scales.strip():
        return []

    scales: list[float] = []
    for raw_scale in raw_scales.split(","):
        raw_scale = raw_scale.strip()
        if not raw_scale:
            continue
        value = to_float(raw_scale)
        if value is None:
            raise ValueError(f"Invalid grid-search scale: {raw_scale}")
        scales.append(value)
    return scales


def vector3(row: dict[str, str], prefix: str) -> tuple[float, float, float] | None:
    values = (
        to_float(row.get(f"{prefix}_x")),
        to_float(row.get(f"{prefix}_y")),
        to_float(row.get(f"{prefix}_z")),
    )
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def vla_xyz(row: dict[str, str]) -> tuple[float, float, float] | None:
    values = tuple(to_float(row.get(field)) for field in XYZ_ACTION_FIELDS)
    if any(value is None for value in values):
        return None
    return values  # type: ignore[return-value]


def distance_3d(a: tuple[float, float, float], b: tuple[float, float, float]) -> float:
    return math.sqrt(sum((left - right) ** 2 for left, right in zip(a, b)))


def clip_value(value: float, limit: float) -> float:
    return max(-limit, min(limit, value))


def adapted_goal(
    ee_pos: tuple[float, float, float],
    action_xyz: tuple[float, float, float],
    scale: float,
    clip: float,
) -> tuple[float, float, float]:
    clipped = tuple(clip_value(value, clip) for value in action_xyz)
    return tuple(position + scale * delta for position, delta in zip(ee_pos, clipped))  # type: ignore[return-value]


def mean(values: list[float]) -> float | None:
    if not values:
        return None
    return sum(values) / len(values)


def format_number(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.6g}"


def format_percent(value: float | None) -> str:
    if value is None:
        return "n/a"
    return f"{value:.2f}%"


def load_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open(newline="", encoding="utf-8") as file:
        return list(csv.DictReader(file))


def analyze_rows(
    rows: list[dict[str, str]],
    phases: set[str],
    scale: float,
    clip: float,
) -> dict[str, object]:
    used_rows = 0
    skipped_phase = 0
    skipped_vla_error = 0
    skipped_missing_action = 0
    skipped_missing_pose = 0

    baseline_distances: list[float] = []
    adapted_distances: list[float] = []

    for row in rows:
        phase = (row.get("phase") or "").strip()
        if phases and phase not in phases:
            skipped_phase += 1
            continue

        if (row.get("vla_error") or "").strip():
            skipped_vla_error += 1
            continue

        action_xyz = vla_xyz(row)
        if action_xyz is None:
            skipped_missing_action += 1
            continue

        ee_pos = vector3(row, "ee_pos")
        scripted_goal = vector3(row, "scripted_ee_goal")
        if ee_pos is None or scripted_goal is None:
            skipped_missing_pose += 1
            continue

        predicted_goal = adapted_goal(ee_pos, action_xyz, scale, clip)
        baseline_distances.append(distance_3d(ee_pos, scripted_goal))
        adapted_distances.append(distance_3d(predicted_goal, scripted_goal))
        used_rows += 1

    baseline_mean = mean(baseline_distances)
    adapted_mean = mean(adapted_distances)
    improvement = None
    if baseline_mean is not None and baseline_mean > 0 and adapted_mean is not None:
        improvement = 100.0 * (baseline_mean - adapted_mean) / baseline_mean

    return {
        "used_rows": used_rows,
        "skipped_phase": skipped_phase,
        "skipped_vla_error": skipped_vla_error,
        "skipped_missing_action": skipped_missing_action,
        "skipped_missing_pose": skipped_missing_pose,
        "baseline_distances": baseline_distances,
        "adapted_distances": adapted_distances,
        "baseline_mean": baseline_mean,
        "adapted_mean": adapted_mean,
        "improvement": improvement,
    }


def grid_search(
    rows: list[dict[str, str]],
    phases: set[str],
    scales: list[float],
    clip: float,
) -> list[dict[str, object]]:
    results: list[dict[str, object]] = []
    for scale in scales:
        report = analyze_rows(rows, phases, scale, clip)
        results.append(
            {
                "scale": scale,
                "used_rows": report["used_rows"],
                "adapted_mean": report["adapted_mean"],
                "improvement": report["improvement"],
            }
        )
    return results


def print_report(
    csv_path: Path,
    phases: set[str],
    scale: float,
    clip: float,
    min_samples: int,
    report: dict[str, object],
    grid_results: list[dict[str, object]],
) -> None:
    phase_filter = ",".join(
        sorted(phases, key=lambda value: (0, int(value)) if value.isdigit() else (1, value))
    )
    if not phase_filter:
        phase_filter = "all"

    print("Offline VLA Action Adapter Report")
    print(f"CSV: {csv_path}")
    print(f"Phase filter: {phase_filter}")
    print(f"Adapter: ee_pos + {scale:.6g} * clip(vla_xyz, +/-{clip:.6g})")
    print()
    print("Rows")
    print(f"Used: {report['used_rows']}")
    print(f"Skipped by phase: {report['skipped_phase']}")
    print(f"Skipped VLA errors: {report['skipped_vla_error']}")
    print(f"Skipped missing action: {report['skipped_missing_action']}")
    print(f"Skipped missing pose/goal: {report['skipped_missing_pose']}")
    print(f"Minimum samples: {min_samples}")
    sample_status = "PASS" if int(report["used_rows"]) >= min_samples else "LOW SAMPLE"
    print(f"Sample status: {sample_status}")
    print()
    print("Distance To Scripted Goal")
    print(f"Baseline ee->scripted mean: {format_number(report['baseline_mean'])}")
    print(f"Adapted predicted->scripted mean: {format_number(report['adapted_mean'])}")
    print(f"Improvement: {format_percent(report['improvement'])}")

    if not grid_results:
        return

    print()
    print("Grid Search")
    best = None
    for result in grid_results:
        adapted_mean = result["adapted_mean"]
        print(
            f"scale={format_number(result['scale'])} "
            f"used={result['used_rows']} "
            f"mean_error={format_number(adapted_mean)} "
            f"improvement={format_percent(result['improvement'])}"
        )
        if adapted_mean is not None and (best is None or adapted_mean < best["adapted_mean"]):
            best = result

    if best is not None:
        print(f"best_scale={format_number(best['scale'])}")


def main() -> int:
    args = parse_args()
    if not args.csv.exists():
        print(f"CSV not found: {args.csv}")
        return 1

    if args.clip < 0:
        print("--clip must be non-negative")
        return 1
    if args.min_samples < 1:
        print("--min-samples must be at least 1")
        return 1

    try:
        grid_scales = parse_scales(args.grid_search_scales)
    except ValueError as error:
        print(error)
        return 1

    rows = load_rows(args.csv)
    phases = parse_phase_filters(args.phase)
    report = analyze_rows(rows, phases, args.scale, args.clip)
    grid_results = grid_search(rows, phases, grid_scales, args.clip)
    print_report(args.csv, phases, args.scale, args.clip, args.min_samples, report, grid_results)

    if int(report["used_rows"]) == 0:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
